# Generated by Django 5.2.8 on 2025-11-26 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_servico_valor'),
        ('cobrancas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobranca',
            name='valor',
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.servico'),
        ),
    ]
