# Generated by Django 5.2.8 on 2025-11-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
